import { FormState } from "@/types";
import { FormType } from "./graphql";
import { v4 } from "uuid";

export const rsvp: FormState = {
  name: "Event RSVP",
  editMode: true,
  isFavorite: false,
  loading: false,
  selectedComponent: "formHeader",
  theme: {
    Header: {
      fontSize: "24",
      fontFamily: "Open Sans",
      text: "<p><strong>Event RSVP</strong></p>",
      image: {
        name: "rsvp.jpg",
        type: "image/jpeg",
        initialDataUrl: "",
        dataUrl:
          "https://res.cloudinary.com/dfcbsf8um/image/upload/v1705866735/rsvp.jpg",
        origin: "client",
      },
    },
    Question: {
      fontSize: "16",
      fontFamily: "Open Sans",
    },
    Text: {
      fontSize: "14",
      fontFamily: "Open Sans",
      text: "<p>Event Address: 123 Your Street Your City, ST 12345</p>",
    },
    primaryColor: "#673ab7",
    secondaryColor: "#e1d8f1",
  },
  items: [
    {
      id: v4(),
      name: "<p>Can you attend?</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Yes, I'll be there",
          order: 1,
        },
        {
          id: v4(),
          value: "Sorry, can't make it",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>What are the names of people attending?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: false,
      options: [],
    },
    {
      id: v4(),
      name: "<p>How did you hear about this event?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Friend",
          order: 1,
        },
        {
          id: v4(),
          value: "Advertisement",
          order: 2,
        },
        {
          id: v4(),
          value: "Newsletter",
          order: 3,
        },
        {
          id: v4(),
          value: "Online",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Comments/questions</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
  ],
};
export const contact: FormState = {
  name: "Contact information",
  editMode: true,
  isFavorite: false,
  loading: false,
  selectedComponent: "formHeader",
  theme: {
    Header: {
      fontSize: "24",
      fontFamily: "Open Sans",
      text: "<p>Contact information</p>",
      image: {
        name: "contact.jpg",
        type: "image/jpeg",
        initialDataUrl: "",
        dataUrl:
          "https://res.cloudinary.com/dfcbsf8um/image/upload/v1705871843/contact.jpg",
        origin: "client",
      },
    },
    Question: {
      fontSize: "16",
      fontFamily: "Open Sans",
    },
    Text: {
      fontSize: "14",
      fontFamily: "Open Sans",
      text: "<p>Description</p>",
    },
    primaryColor: "#4285f4",
    secondaryColor: "#d9e7fd",
  },
  items: [
    {
      id: v4(),
      name: "<p>Name</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: true,
      options: [],
    },
    {
      id: v4(),
      name: "<p>Email</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: true,
      options: [],
    },
    {
      id: v4(),
      name: "<p>Address</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: true,
      options: [],
    },
    {
      id: v4(),
      name: "<p>Phone number</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: true,
      options: [],
    },
    {
      id: v4(),
      name: "<p>Comments</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: false,
      options: [],
    },
  ],
};
export const registration: FormState = {
  name: "Event registration",
  editMode: true,
  isFavorite: false,
  loading: false,
  selectedComponent: "formHeader",
  theme: {
    Header: {
      fontSize: "24",
      fontFamily: "Open Sans",
      text: "<p>Event registration</p>",
      image: {
        name: "registration.jpg",
        type: "image/jpeg",
        initialDataUrl: "",
        dataUrl:
          "https://res.cloudinary.com/dfcbsf8um/image/upload/v1705872636/registration.jpg",
        origin: "client",
      },
    },
    Question: {
      fontSize: "16",
      fontFamily: "Open Sans",
    },
    Text: {
      fontSize: "14",
      fontFamily: "Open Sans",
      text: "<p>Event Timing: January 4th-6th, 2016</p><p>Event Address: 123 Your Street Your City, ST 12345</p><p>Contact us at (123) 456-7890 or no_reply@example.com</p>",
    },
    primaryColor: "#ff9800",
    secondaryColor: "#ffeacc",
  },
  items: [
    {
      id: v4(),
      name: "<p>Name</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: true,
      options: [],
    },
    {
      id: v4(),
      name: "<p>Email</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: false,
      options: [],
    },
    {
      id: v4(),
      name: "<p>Organization</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: false,
      options: [],
    },
    {
      id: v4(),
      name: "<p>What days will you attend?</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.MultipleChoice,
      required: false,
      options: [
        {
          id: v4(),
          value: "Day 1",
          order: 1,
        },
        {
          id: v4(),
          value: "Day 2",
          order: 2,
        },
        {
          id: v4(),
          value: "Day 3",
          order: 3,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Dietary restrictions</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: false,
      options: [
        {
          id: v4(),
          value: "None",
          order: 1,
        },
        {
          id: v4(),
          value: "Vegetarian",
          order: 2,
        },
        {
          id: v4(),
          value: "Vegan",
          order: 3,
        },
        {
          id: v4(),
          value: "Kosher",
          order: 4,
        },
        {
          id: v4(),
          value: "Gluten-free",
          order: 5,
        },
      ],
    },
  ],
};
