import { FormState } from "@/types";
import { v4 } from "uuid";

enum FormType {
  Date = "DATE",
  Dropdown = "DROPDOWN",
  LinearScale = "LINEAR_SCALE",
  Long = "LONG",
  MultipleChoice = "MULTIPLE_CHOICE",
  Short = "SHORT",
  SingleChoice = "SINGLE_CHOICE",
}

export const rsvp: FormState = {
  name: "Event RSVP",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Header: {
      fontSize: "24",
      fontFamily: "Open Sans",
      text: "<p><strong>Event RSVP</strong></p>",
      image: {
        name: "rsvp.jpg",
        type: "image/jpeg",
        initialDataUrl: "",
        dataUrl:
          "https://res.cloudinary.com/dfcbsf8um/image/upload/v1705866735/rsvp.jpg",
        origin: "client",
      },
    },
    Question: {
      fontSize: "16",
      fontFamily: "Open Sans",
    },
    Text: {
      fontSize: "14",
      fontFamily: "Open Sans",
      text: "<p>Event Address: 123 Your Street Your City, ST 12345</p>",
    },
    primaryColor: "#673ab7",
    secondaryColor: "#e1d8f1",
  },
  items: [
    {
      id: v4(),
      name: "<p>Can you attend?</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Yes, I'll be there",
          order: 1,
        },
        {
          id: v4(),
          value: "Sorry, can't make it",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>What are the names of people attending?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: false,
      options: [],
    },
    {
      id: v4(),
      name: "<p>How did you hear about this event?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Friend",
          order: 1,
        },
        {
          id: v4(),
          value: "Advertisement",
          order: 2,
        },
        {
          id: v4(),
          value: "Newsletter",
          order: 3,
        },
        {
          id: v4(),
          value: "Online",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Comments/questions</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
  ],
  deletedItems: [],
};
export const orderRequest: FormState = {
  name: "Order request",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Text: {
      text: "<p>After you fill out this order request, we will contact you to go over details and availability before the order is completed. If you would like faster service and direct information on current stock and pricing please contact us at Contact us at (123) 456-7890 or no_reply@example.com</p>",
      fontSize: "14",
      fontFamily: "Open Sans",
    },
    Header: {
      text: "<p>Order request</p>",
      image: {
        name: "form-header-d6bd2c2a-4b6c-4360-87ae-38faed5f0e17",
        type: "",
        origin: "client",
        dataUrl:
          "http://res.cloudinary.com/dfcbsf8um/image/upload/v1706978090/d6bd2c2a-4b6c-4360-87ae-38faed5f0e17/vbn3buf7livkbnzblwi6.jpg",
        initialDataUrl: "",
      },
      fontSize: "24",
      fontFamily: "Open Sans",
    },
    Question: {
      fontSize: "16",
      fontFamily: "Open Sans",
    },
    primaryColor: "#6c1919",
    secondaryColor: "#f7f3f4",
  },
  items: [
    {
      id: v4(),
      name: "<p>Are you a new or existing customer?</p>",
      order: 1,
      required: false,
      type: FormType.SingleChoice,
      options: [
        {
          id: v4(),
          order: 1,
          value: "I am a new customer",
        },
        {
          id: v4(),
          order: 2,
          value: "I am an existing customer",
        },
      ],
      origin: "client",
    },
    {
      id: v4(),
      name: "<p>What is the item you would like to order?</p>",
      order: 2,
      required: false,
      type: FormType.Short,
      options: [],
      origin: "client",
    },
    {
      id: v4(),
      name: "<p>What color(s) would you like to order?</p>",
      order: 3,
      required: false,
      type: FormType.MultipleChoice,
      options: [
        {
          id: v4(),
          order: 1,
          value: "Color 1",
        },
        {
          id: v4(),
          order: 2,
          value: "Color 2",
        },
        {
          id: v4(),
          order: 3,
          value: "Color 3",
        },
        {
          id: v4(),
          order: 4,
          value: "Color 4",
        },
      ],
      origin: "client",
    },
    {
      id: v4(),
      name: "<p>Your name</p>",
      order: 4,
      required: true,
      type: FormType.Short,
      options: [],
      origin: "client",
    },
    {
      id: v4(),
      name: "<p>Phone number</p>",
      order: 5,
      required: true,
      type: FormType.Short,
      options: [],
      origin: "client",
    },
    {
      id: v4(),
      name: "<p>Preferred contact method</p>",
      order: 6,
      required: false,
      type: FormType.MultipleChoice,
      options: [
        {
          id: v4(),
          order: 1,
          value: "Phone",
        },
        {
          id: v4(),
          order: 2,
          value: "Email",
        },
      ],
      origin: "client",
    },
    {
      id: v4(),
      name: "<p>Questions and comments</p>",
      order: 7,
      required: false,
      type: FormType.Long,
      options: [],
      origin: "client",
    },
  ],
  deletedItems: [],
};
export const jobApplication: FormState = {
  name: "Job application",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Text: {
      text: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur quis sem odio. Sed commodo vestibulum leo, sit amet tempus odio consectetur in. Mauris dolor elit, dignissim mollis feugiat maximus, faucibus et eros.</p>",
      fontSize: "14",
      fontFamily: "Open Sans",
    },
    Header: {
      text: "<p>Job application</p>",
      image: {
        name: "job-application",
        type: "",
        origin: "client",
        dataUrl:
          "http://res.cloudinary.com/dfcbsf8um/image/upload/v1706977632/6a4c018f-c2f7-4342-86f3-7247a3425080/xde6zxrdglgqssljtfei.jpg",
        initialDataUrl: "",
      },
      fontSize: "24",
      fontFamily: "Open Sans",
    },
    Question: {
      fontSize: "16",
      fontFamily: "Open Sans",
    },
    primaryColor: "#1b7c6b",
    secondaryColor: "#d1e5e1",
  },
  items: [
    {
      id: v4(),
      name: "<p>Full name</p>",
      order: 1,
      required: true,
      type: FormType.Short,
      options: [],
      origin: "client",
    },
    {
      id: v4(),
      name: "<p>Email</p>",
      order: 2,
      required: true,
      type: FormType.Short,
      options: [],
      origin: "client",
    },
    {
      id: v4(),
      name: "<p>Phone number</p>",
      order: 3,
      required: true,
      type: FormType.Short,
      options: [],
      origin: "client",
    },
    {
      id: v4(),
      name: "<p>Which position(s) are you interested in?</p>",
      order: 4,
      required: true,
      type: FormType.MultipleChoice,
      options: [
        {
          id: v4(),
          order: 1,
          value: "Position 1",
        },
        {
          id: v4(),
          order: 2,
          value: "Position 2",
        },
        {
          id: v4(),
          order: 3,
          value: "Position 3",
        },
      ],
      origin: "client",
    },
    {
      id: v4(),
      name: "<p>Submit your cover letter or resume</p>",
      order: 5,
      required: false,
      type: FormType.Long,
      options: [],
      origin: "client",
    },
  ],
  deletedItems: [],
};

export const employeeSurvey: FormState = {
  name: "Employee Satisfaction Survey",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Header: {
      fontSize: "24",
      fontFamily: "Open Sans",
      text: "<p>Employee Satisfaction Survey</p>",
    },
    Question: {
      fontSize: "16",
      fontFamily: "Open Sans",
    },
    Text: {
      fontSize: "14",
      fontFamily: "Open Sans",
      text: "<p>Please fill out this survey to help us understand your satisfaction level.</p>",
    },
    primaryColor: "#db4437",
    secondaryColor: "#f1b4af",
  },
  items: [
    {
      id: v4(),
      name: "<p>Overall, how satisfied are you with your job?</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          label: "Very Dissatisfied",
          order: 1,
          value: "1",
        },
        {
          id: v4(),
          label: "Very Satisfied",
          order: 2,
          value: "10",
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Which aspects of your job do you enjoy the most?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.MultipleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Work Environment",
          order: 1,
        },
        {
          id: v4(),
          value: "Team Collaboration",
          order: 2,
        },
        {
          id: v4(),
          value: "Growth Opportunities",
          order: 3,
        },
        {
          id: v4(),
          value: "Company Culture",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Do you feel valued at work?</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Yes",
          order: 1,
        },
        {
          id: v4(),
          value: "No",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>How often do you receive recognition for your work?</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.Dropdown,
      required: true,
      options: [
        {
          id: v4(),
          value: "Daily",
          order: 1,
        },
        {
          id: v4(),
          value: "Weekly",
          order: 2,
        },
        {
          id: v4(),
          value: "Monthly",
          order: 3,
        },
        {
          id: v4(),
          value: "Rarely",
          order: 4,
        },
        {
          id: v4(),
          value: "Never",
          order: 5,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>What improvements would you like to see in the workplace?</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
    {
      id: v4(),
      name: "<p>Please rate your work-life balance.</p>",
      order: 6,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          label: "Poor",
          order: 1,
          value: "1",
        },
        {
          id: v4(),
          label: "Excellent",
          order: 2,
          value: "10",
        },
      ],
    },
    {
      id: v4(),
      name: "<p>What is your preferred method of communication at work?</p>",
      order: 7,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: false,
      options: [
        {
          id: v4(),
          value: "Email",
          order: 1,
        },
        {
          id: v4(),
          value: "Phone",
          order: 2,
        },
        {
          id: v4(),
          value: "In-Person",
          order: 3,
        },
        {
          id: v4(),
          value: "Messaging App",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Do you have any additional comments or suggestions?</p>",
      order: 8,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
  ],
  deletedItems: [],
};

export const travelSurvey: FormState = {
  name: "Travel Experience Feedback",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Header: {
      fontSize: "24",
      fontFamily: "Open Sans",
      text: "<p>Travel Experience Feedback</p>",
    },
    Question: {
      fontSize: "16",
      fontFamily: "Open Sans",
    },
    Text: {
      fontSize: "14",
      fontFamily: "Open Sans",
      text: "<p>We appreciate you taking the time to provide feedback on your recent travel experience with us. Your input helps us improve our services.</p>",
    },
    primaryColor: "#2196f3",
    secondaryColor: "#e3f2fd",
  },
  items: [
    {
      id: v4(),
      name: "<p>How would you rate the overall quality of your trip?</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          label: "Poor",
          order: 1,
          value: "1",
        },
        {
          id: v4(),
          label: "Excellent",
          order: 2,
          value: "10",
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Which aspects of the trip did you enjoy the most?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.MultipleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Accommodation",
          order: 1,
        },
        {
          id: v4(),
          value: "Sightseeing",
          order: 2,
        },
        {
          id: v4(),
          value: "Food",
          order: 3,
        },
        {
          id: v4(),
          value: "Guided Tours",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>How satisfied were you with the customer service during your trip?</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Very Satisfied",
          order: 1,
        },
        {
          id: v4(),
          value: "Satisfied",
          order: 2,
        },
        {
          id: v4(),
          value: "Neutral",
          order: 3,
        },
        {
          id: v4(),
          value: "Dissatisfied",
          order: 4,
        },
        {
          id: v4(),
          value: "Very Dissatisfied",
          order: 5,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>What could we improve for future trips?</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
    {
      id: v4(),
      name: "<p>Would you recommend our travel service to others?</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Yes",
          order: 1,
        },
        {
          id: v4(),
          value: "No",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Please provide any additional comments or suggestions.</p>",
      order: 6,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
  ],
  deletedItems: [],
};

export const healthAssessment: FormState = {
  name: "Health and Wellness Assessment",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Header: {
      fontSize: "24",
      fontFamily: "Open Sans",
      text: "<p>Health and Wellness Assessment</p>",
    },
    Question: {
      fontSize: "16",
      fontFamily: "Open Sans",
    },
    Text: {
      fontSize: "14",
      fontFamily: "Open Sans",
      text: "<p>Your well-being is important to us. Please answer the following questions to help us better understand your health and wellness needs.</p>",
    },
    primaryColor: "#4caf50",
    secondaryColor: "#e8f5e9",
  },
  items: [
    {
      id: v4(),
      name: "<p>How often do you exercise in a week?</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Never",
          order: 1,
        },
        {
          id: v4(),
          value: "1-2 times",
          order: 2,
        },
        {
          id: v4(),
          value: "3-4 times",
          order: 3,
        },
        {
          id: v4(),
          value: "5 or more times",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Rate your current stress level:</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          label: "Low",
          order: 1,
          value: "1",
        },
        {
          id: v4(),
          label: "High",
          order: 2,
          value: "10",
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Which of the following best describes your diet?</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.MultipleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Balanced and healthy",
          order: 1,
        },
        {
          id: v4(),
          value: "Mostly healthy with occasional indulgences",
          order: 2,
        },
        {
          id: v4(),
          value: "Balanced but often skip meals",
          order: 3,
        },
        {
          id: v4(),
          value: "Unhealthy and irregular",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Do you have any current health conditions that we should be aware of?</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
    {
      id: v4(),
      name: "<p>How many hours of sleep do you get on average per night?</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Less than 5 hours",
          order: 1,
        },
        {
          id: v4(),
          value: "5-6 hours",
          order: 2,
        },
        {
          id: v4(),
          value: "7-8 hours",
          order: 3,
        },
        {
          id: v4(),
          value: "More than 8 hours",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Any additional comments or suggestions for improving your wellness program?</p>",
      order: 6,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
  ],
  deletedItems: [],
};

export const petAdoptionInquiry: FormState = {
  name: "Pet Adoption Inquiry",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Header: {
      fontSize: "24",
      fontFamily: "Lobster",
      text: "<p>Pet Adoption Inquiry</p>",
    },
    Question: {
      fontSize: "18",
      fontFamily: "Barlow",
    },
    Text: {
      fontSize: "16",
      fontFamily: "Lora",
      text: "<p>We’re excited to help you find your new furry friend! Please provide us with some information to help us match you with the perfect pet.</p>",
    },
    primaryColor: "#ffab91",
    secondaryColor: "#ffe0b2",
  },
  items: [
    {
      id: v4(),
      name: "<p>What type of pet are you interested in?</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Dog",
          order: 1,
        },
        {
          id: v4(),
          value: "Cat",
          order: 2,
        },
        {
          id: v4(),
          value: "Other",
          order: 3,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>What is your preferred age range for the pet?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          label: "Puppy/Kitten",
          order: 1,
          value: "1",
        },
        {
          id: v4(),
          label: "Senior",
          order: 2,
          value: "10",
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Do you have any preferences for the pet’s breed?</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.Short,
      required: false,
      options: [],
    },
    {
      id: v4(),
      name: "<p>What is your experience with pets?</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "First-time pet owner",
          order: 1,
        },
        {
          id: v4(),
          value: "Experienced pet owner",
          order: 2,
        },
        {
          id: v4(),
          value: "Currently have pets",
          order: 3,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>What is your living situation?</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.MultipleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "House with yard",
          order: 1,
        },
        {
          id: v4(),
          value: "Apartment",
          order: 2,
        },
        {
          id: v4(),
          value: "Other",
          order: 3,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Any additional information or special requests?</p>",
      order: 6,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
  ],
  deletedItems: [],
};

export const volunteerInterestForm: FormState = {
  name: "Volunteer Interest Form",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Header: {
      fontSize: "20",
      fontFamily: "Alegreya",
      text: "<p>Volunteer Interest Form</p>",
    },
    Question: {
      fontSize: "17",
      fontFamily: "Barlow",
    },
    Text: {
      fontSize: "15",
      fontFamily: "Lora",
      text: "<p>Thank you for your interest in volunteering with us. Please fill out the form below to let us know more about your interests and availability.</p>",
    },
    primaryColor: "#4caf50",
    secondaryColor: "#e8f5e9",
  },
  items: [
    {
      id: v4(),
      name: "<p>Which areas are you interested in volunteering?</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.MultipleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Community Outreach",
          order: 1,
        },
        {
          id: v4(),
          value: "Event Planning",
          order: 2,
        },
        {
          id: v4(),
          value: "Fundraising",
          order: 3,
        },
        {
          id: v4(),
          value: "Administrative Support",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>What is your availability?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.Dropdown,
      required: true,
      options: [
        {
          id: v4(),
          value: "Weekdays",
          order: 1,
        },
        {
          id: v4(),
          value: "Weekends",
          order: 2,
        },
        {
          id: v4(),
          value: "Evenings",
          order: 3,
        },
        {
          id: v4(),
          value: "Flexible",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Why do you want to volunteer with us?</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: true,
      options: [],
    },
    {
      id: v4(),
      name: "<p>Do you have any previous volunteer experience?</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: false,
      options: [
        {
          id: v4(),
          value: "Yes",
          order: 1,
        },
        {
          id: v4(),
          value: "No",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Additional comments or questions?</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
  ],
  deletedItems: [],
};

export const demographicInformation: FormState = {
  name: "Demographic Information Survey",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Header: {
      fontSize: "24",
      fontFamily: "Barlow",
      text: "<p>Demographic Information Survey</p>",
    },
    Question: {
      fontSize: "18",
      fontFamily: "Nunito",
    },
    Text: {
      fontSize: "16",
      fontFamily: "Lato",
      text: "<p>Please provide us with some basic demographic information to help us understand the diversity of our audience.</p>",
    },
    primaryColor: "#3f51b5",
    secondaryColor: "#c5cae9",
  },
  items: [
    {
      id: v4(),
      name: "<p>Age Group</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.Dropdown,
      required: true,
      options: [
        {
          id: v4(),
          value: "Under 18",
          order: 1,
        },
        {
          id: v4(),
          value: "18-24",
          order: 2,
        },
        {
          id: v4(),
          value: "25-34",
          order: 3,
        },
        {
          id: v4(),
          value: "35-44",
          order: 4,
        },
        {
          id: v4(),
          value: "45-54",
          order: 5,
        },
        {
          id: v4(),
          value: "55-64",
          order: 6,
        },
        {
          id: v4(),
          value: "65 and over",
          order: 7,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Gender</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Male",
          order: 1,
        },
        {
          id: v4(),
          value: "Female",
          order: 2,
        },
        {
          id: v4(),
          value: "Non-binary",
          order: 3,
        },
        {
          id: v4(),
          value: "Prefer not to say",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Highest Level of Education</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.Dropdown,
      required: true,
      options: [
        {
          id: v4(),
          value: "High School",
          order: 1,
        },
        {
          id: v4(),
          value: "Associate's Degree",
          order: 2,
        },
        {
          id: v4(),
          value: "Bachelor's Degree",
          order: 3,
        },
        {
          id: v4(),
          value: "Master's Degree",
          order: 4,
        },
        {
          id: v4(),
          value: "Doctoral Degree",
          order: 5,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Employment Status</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Employed full-time",
          order: 1,
        },
        {
          id: v4(),
          value: "Employed part-time",
          order: 2,
        },
        {
          id: v4(),
          value: "Unemployed",
          order: 3,
        },
        {
          id: v4(),
          value: "Retired",
          order: 4,
        },
        {
          id: v4(),
          value: "Student",
          order: 5,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Annual Income</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.Dropdown,
      required: true,
      options: [
        {
          id: v4(),
          value: "Below $10k",
          order: 1,
        },
        {
          id: v4(),
          value: "$10k-$50k",
          order: 2,
        },
        {
          id: v4(),
          value: "$50k-$100k",
          order: 3,
        },
        {
          id: v4(),
          value: "$100k-$150k",
          order: 4,
        },
        {
          id: v4(),
          value: "Over $150k",
          order: 5,
        },
      ],
    },
  ],
  deletedItems: [],
};

export const patientSatisfactionSurvey: FormState = {
  name: "Patient Satisfaction Survey",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Header: {
      fontSize: "23",
      fontFamily: "Merriweather",
      text: "<p>Patient Satisfaction Survey</p>",
    },
    Question: {
      fontSize: "17",
      fontFamily: "Barlow",
    },
    Text: {
      fontSize: "15",
      fontFamily: "Lora",
      text: "<p>Your feedback is important to us. Please take a moment to share your experience.</p>",
    },
    primaryColor: "#4caf50",
    secondaryColor: "#e8f5e9",
  },
  items: [
    {
      id: v4(),
      name: "<p>How satisfied are you with the quality of care you received?</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          value: "1",
          order: 1,
        },
        {
          id: v4(),
          value: "10",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>How would you rate the professionalism of the staff?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          value: "1",
          order: 1,
        },
        {
          id: v4(),
          value: "10",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Were you satisfied with the waiting time?</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Very Satisfied",
          order: 1,
        },
        {
          id: v4(),
          value: "Somewhat Satisfied",
          order: 2,
        },
        {
          id: v4(),
          value: "Neutral",
          order: 3,
        },
        {
          id: v4(),
          value: "Somewhat Dissatisfied",
          order: 4,
        },
        {
          id: v4(),
          value: "Very Dissatisfied",
          order: 5,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>How likely are you to recommend our clinic to others?</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          value: "1",
          order: 1,
        },
        {
          id: v4(),
          value: "10",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Do you have any additional comments or suggestions?</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
  ],
  deletedItems: [],
};

export const socialMediaUsage: FormState = {
  name: "Social Media Usage Survey",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Header: {
      fontSize: "22",
      fontFamily: "Nunito",
      text: "<p>Social Media Usage Survey</p>",
    },
    Question: {
      fontSize: "20",
      fontFamily: "Roboto",
    },
    Text: {
      fontSize: "16",
      fontFamily: "Lato",
      text: "<p>We appreciate your input in helping us understand social media habits better.</p>",
    },
    primaryColor: "#EF476F",
    secondaryColor: "#fac7d3",
  },
  items: [
    {
      id: v4(),
      name: "<p>How often do you use social media?</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.Dropdown,
      required: true,
      options: [
        {
          id: v4(),
          value: "Multiple times a day",
          order: 1,
        },
        {
          id: v4(),
          value: "Once a day",
          order: 2,
        },
        {
          id: v4(),
          value: "A few times a week",
          order: 3,
        },
        {
          id: v4(),
          value: "Rarely",
          order: 4,
        },
        {
          id: v4(),
          value: "Never",
          order: 5,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Which social media platform do you use the most?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.MultipleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Facebook",
          order: 1,
        },
        {
          id: v4(),
          value: "Instagram",
          order: 2,
        },
        {
          id: v4(),
          value: "Twitter",
          order: 3,
        },
        {
          id: v4(),
          value: "TikTok",
          order: 4,
        },
        {
          id: v4(),
          value: "LinkedIn",
          order: 5,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>How much time do you spend on social media each day?</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          value: "1",
          order: 1,
        },
        {
          id: v4(),
          value: "10",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Do you feel that social media has a positive or negative impact on your life?</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Positive",
          order: 1,
        },
        {
          id: v4(),
          value: "Negative",
          order: 2,
        },
        {
          id: v4(),
          value: "Neutral",
          order: 3,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>If you could change one thing about social media, what would it be?</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
  ],
  deletedItems: [],
};

export const onlineShoppingExperience: FormState = {
  name: "Online Shopping Experience Survey",
  editMode: true,
  isFavorite: false,
  loading: false,
  loadingThumbnail: "",
  selectedComponent: "formHeader",
  activeTab: 0,
  operation: "",
  theme: {
    Header: {
      fontSize: "22",
      fontFamily: "Raleway",
      text: "<p>Online Shopping Experience Survey</p>",
    },
    Question: {
      fontSize: "18",
      fontFamily: "Inter",
    },
    Text: {
      fontSize: "16",
      fontFamily: "Barlow",
      text: "<p>We value your feedback on your online shopping experience. Please help us improve by answering the following questions.</p>",
    },
    primaryColor: "#009688",
    secondaryColor: "#e0f2f1",
  },
  items: [
    {
      id: v4(),
      name: "<p>How easy was it to navigate our website?</p>",
      order: 1,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          value: "1",
          order: 1,
        },
        {
          id: v4(),
          value: "10",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>How satisfied are you with the product selection available?</p>",
      order: 2,
      origin: "client",
      section: 0,
      type: FormType.LinearScale,
      required: true,
      options: [
        {
          id: v4(),
          value: "1",
          order: 1,
        },
        {
          id: v4(),
          value: "10",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>What was your overall experience with our customer service?</p>",
      order: 3,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Excellent",
          order: 1,
        },
        {
          id: v4(),
          value: "Good",
          order: 2,
        },
        {
          id: v4(),
          value: "Average",
          order: 3,
        },
        {
          id: v4(),
          value: "Poor",
          order: 4,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Would you recommend our website to others?</p>",
      order: 4,
      origin: "client",
      section: 0,
      type: FormType.SingleChoice,
      required: true,
      options: [
        {
          id: v4(),
          value: "Yes",
          order: 1,
        },
        {
          id: v4(),
          value: "No",
          order: 2,
        },
      ],
    },
    {
      id: v4(),
      name: "<p>Any additional comments or suggestions?</p>",
      order: 5,
      origin: "client",
      section: 0,
      type: FormType.Long,
      required: false,
      options: [],
    },
  ],
  deletedItems: [],
};
